CREATE TABLE energyuser (
  id INT NOT NULL PRIMARY KEY,
  username VARCHAR(999) NOT NULL,
  passwordhash VARCHAR(999) NOT NULL,
  role VARCHAR(999) NOT NULL
);

CREATE SEQUENCE seq_energyuser START 1;